project2/helloengineer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'helloengineer'

urlpatterns = [
    path('', views.index, name='index'),
    path('group_list/', views.GroupList.as_view(), name='group_list'),
    path('group_create/', views.GroupCreate, name='group_create'),
    path('group_thread/<int:pk>/', views.ThreadView.as_view(), name='group_thread'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="helloengineer/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="helloengineer:index"), name='logout'),
    path('userpage/<int:user_pk>/', views.userpage, name='userpage'),
    path('mypage/<int:user_pk>/', views.mypage, name='mypage'),
    path('profileupdate/<int:pk>/', views.profileupdate, name='profileupdate'),
    path('delete/<int:group_pk>/', views.delete_group, name='delete'),
]

project2/project2/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include

urlpatterns = [
    path('asdumpienr/', admin.site.urls),
    path('helloengineer/', include ('helloengineer.urls')),
]

from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project2/helloengineer/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils import timezone
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

GENDER_CHOICES = (
	('1', '女性'),
	('2', '男性'),
	('3', '未設定'),
)

class Profile(models.Model):
	user_img = models.ImageField("アイコン", upload_to='helloengineer/users',blank=True, null=True)
	income = models.CharField("年収", max_length=15, default='未設定')
	gender = models.CharField("性別", max_length=3, choices=GENDER_CHOICES, blank=True, default=3)
	birthday = models.DateField("生年月日", blank=True, null=True)
	intro = models.TextField("自己紹介", max_length=400,blank=True, null=True)
	user = models.OneToOneField(User, on_delete=models.CASCADE, default='未設定')
	
	@receiver(post_save, sender=User)
	def create_profile(sender, **kwargs):
		if kwargs['created']:
			user_profile = Profile.objects.get_or_create(user=kwargs['instance'])
	
	def __str__(self):
		return str(self.user)

class Group(models.Model):
	title = models.CharField('グループ名',max_length=50,validators=[MinLengthValidator(1)])
	group_img = models.ImageField('イメージ画像', upload_to='helloengineer/groups',blank=True, null=True)
	create_user = models.ForeignKey(User, on_delete=models.CASCADE)
	created_at = models.DateTimeField('作成日', default=timezone.now)
	
	def __str__(self):
		return self.title

class Comment(models.Model):
	text = models.TextField('本文')
	post = models.ForeignKey(Group, verbose_name='紐づくグループ', on_delete=models.CASCADE)
	created_at = models.DateTimeField('作成日', default=timezone.now)
	create_user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.text[:10]

project2/helloengineer/forms.py
from django import forms
from .models import Group, Comment, Profile
from django.contrib.auth.models import User

class SignUpForm(forms.Form):
    username = forms.CharField(label='ユーザー名', widget=forms.TextInput)
    enter_password = forms.CharField(label='パスワード', widget=forms.PasswordInput)
    retype_password = forms.CharField(label='パスワード確認', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('The username has been already taken.')
        return username

    def clean_enter_password(self):
        password = self.cleaned_data.get('enter_password')
        if len(password) < 5:
            raise forms.ValidationError('Password must contain 5 or more characters.')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('enter_password')
        retyped = self.cleaned_data.get('retype_password')
        if password and retyped and (password != retyped):
            self.add_error('retype_password', 'This does not match with the above.')

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('enter_password')
        new_user = User.objects.create_user(username = username)
        new_user.set_password(password)
        new_user.save()

class GroupCreateForm(forms.ModelForm):
    
    class Meta:
        model=Group
        fields=("title", "group_img")
        
class CommentCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = ('text',)
        
class ProfileUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Profile
        widgets = {
            'birthday': forms.SelectDateWidget(years=[x for x in range(1945, 2017)])
        }
        fields = (
            "user_img", "income", "gender", "birthday", "intro"
        )
        

project2/helloengineer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from django.views import generic
from .models import Group, Comment, Profile
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.views.generic.edit import ModelFormMixin

def index(request):
	return render(request,'helloengineer/index.html')
	
def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			new_user=form.save()
			input_username = form.cleaned_data['username']
			input_password = form.cleaned_data['enter_password']
			new_user = authenticate(username=input_username, password=input_password)
			if new_user is not None:
				login(request, new_user)
				return render(request,'helloengineer/userpage.html')
	else:
		form = SignUpForm()

	context = {'form':form}
	return render(request, 'helloengineer/signup.html', context)
	

#グループ一覧表示
class GroupList(generic.ListView):
	model=Group
	template_name = 'helloengineer/group_list.html'
	paginate_by=6
	
	def get_queryset(self):
		queryset=Group.objects.order_by('-created_at')
		keyword=self.request.GET.get('keyword')
		if keyword:
			queryset=queryset.filter(title__icontains=keyword)
		return queryset

#グループ作成
@login_required
def GroupCreate(request):
	form=GroupCreateForm(request.POST, request.FILES or None)
	
	if request.method=='POST' and form.is_valid():
		group = form.save(commit=False)
		group.create_user = request.user
		group.save()
		return redirect('helloengineer:group_list')

	context={
			'form':form
	}
	return render(request,'helloengineer/group_create.html',context)
		
#グループ詳細ページ
class ThreadView(ModelFormMixin, generic.DetailView):
	model = Group
	template_name = 'helloengineer/group_thread.html'
	form_class = CommentCreateForm

	def form_valid(self, form):
		group_pk = self.kwargs['pk']
		comment = form.save(commit=False)
		comment.create_user = self.request.user
		comment.post = get_object_or_404(Group, pk=group_pk)
		comment.save()
		return redirect('helloengineer:group_thread', pk=group_pk)
		
	def post(self, request, *args, **kwargs):
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			self.object = self.get_object()
			return self.form_invalid(form)

#自分のページを表示
@login_required
def mypage(request, user_pk):
	mypage=get_object_or_404(User,pk=user_pk)
	
	return render(request,'helloengineer/mypage.html')

#別ユーザのページを表示
def userpage(request,user_pk):
	user=get_object_or_404(User,pk=user_pk)
	
	context={
		'user':user
	}
	return render(request,'helloengineer/userpage.html',context)
	
#プロフィールを更新
@login_required
def profileupdate(request,pk):
	profile=get_object_or_404(Profile,pk=pk)
	
	form=ProfileUpdateForm(request.POST, request.FILES or None, instance=profile)
	
	if request.method=='POST' and form.is_valid():
		profile = form.save(commit=False)
		profile.user = request.user
		form.save()
		return render(request,'helloengineer/mypage.html')
		
	context={
		'form':form
	}
	return render(request,'helloengineer/profileupdate.html',context)

#グループを削除
def delete_group(request, group_pk):
	group = get_object_or_404(Group, pk=group_pk)
	group.delete()
	return render(request,'helloengineer/mypage.html')
	

project2/helloengineer/templates/helloengineer/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>Hello Engineer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,user-scalable=yes">
    <!-- Required meta tags -->
    <meta charset="utf-8">

    {% block header %}
    {% endblock %}
  </head>
  <header>
    <div class="header">
      <input type="checkbox" id="hum_op"><label class="op" for="hum_op">MENU</label>
      <ul>
        {% if user.id  %}
          <li class="headerbtn"><a href="{% url 'helloengineer:mypage' user.pk %}">マイページ</a></li>
        {% else %}
          <li class="headerbtn"><a href="/helloengineer/login">ログイン</a></li>
        {% endif %}
        <li><a href="/helloengineer/group_list">グループ一覧</a></li>
      </ul>
      <div class="header-logo"><a href="/helloengineer">Hello Engineer</a></div>
    </div>
  </header>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

project2/helloengineer/templates/helloengineer/group_confirm_delete.html
{% extends 'helloengineer/base.html' %}

{% block content %}
<form action="" method="POST">
  <p>こちらのデータを削除します。</p>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

project2/helloengineer/templates/helloengineer/group_create.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/form.css' %}">
{% endblock %}

{% block content %}
  <h2>グループ作成</h2>
  <div class="center">
    <form action="" method="POST" enctype="multipart/form-data">
    <div class="sheet">
      {% for field in form %}
        <div class="elem">
          {{ field.label }}:
          {{ field }}
        </div>
      {% endfor %}
      <button type="submit" class="create_button">作成</button>
      {% csrf_token %}
    </div>
    </form>
  </div>
{% endblock %}

project2/helloengineer/templates/helloengineer/group_list.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/group_list.css' %}">
{% endblock %}

{% block content %}
  <h1>グループ一覧</h1>
  <form class="serch1" method="GET" action="{% url 'helloengineer:group_list' %}">
    <input class="serch2" type="text" placeholder="Search" aria-label="Search" name="keyword">
    <button classs="searchbutton" type="submit">serach</button>
  </form>
  <div class="group_center">
    {% for group in group_list %}
      <div class="group_img_and_title"><a href="{% url 'helloengineer:group_thread' group.pk %}">
        {% if group.group_img %}
          <img class="groupimg" src="{{ group.group_img.url }}" alt="{{ group.title }}">
        {% else %}
          <img class="groupimg" src="{% static 'helloengineer/img/group_defo.jpg' %}" alt="{{ group.title }}">
        {% endif %}
          <h3>{{ group.title }}</h3>
      </a>
      </div>
    {% endfor %}
  </div>

  {% include 'helloengineer/page.html' %}

{% endblock %}

project2/helloengineer/templates/helloengineer/group_thread.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/group_thread.css' %}">
{% endblock %}

{% block content %}
  <h2>{{ group.title }}の掲示板です</h2>
  {% for comment in group.comment_set.all %}
    <div class="comments"><a href="{% url 'helloengineer:userpage' comment.create_user.pk %}">
      <p>
        {{ comment.text | linebreaksbr }}
      </p>
    </a>
    </div>
    <div class="blank"></div>
  {% endfor %}
  <form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
          {{ field }}
          {{ field.errors }}
      </div>
    {% endfor %}
    {% csrf_token %}
    {% if user.id  %}
      <button type="submit" class="btn-primary">送信</button>
    {% else %}
      <button type="button" onclick='return confirm("投稿するにはログインが必要です");' class="btn-primary">送信</button>
    {% endif %}
  </form>
{% endblock %}

project2/helloengineer/templates/helloengineer/index.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/index.css' %}">
{% endblock %}

{% block content %}
  <div class="center">
    <div class="sheet">
      <h2>【使い方】</h2>
      <div class="elem">
        <h3 id="index_elem1">・エンジニアの会話をのぞいてみましょう</h3>
        <p>グループ一覧から気になるグループをクリック</p>
      </div>
      <div class="elem">
        <h3>・お話してみましょう</h3>
        <p>ログインし、気になるグループをクリック</p>
        <p>一番下の『投稿』ボタンをクリック</p>
      </div>
      <div class="elem">
        <h3>・気になるグループがありませんか?</h3>
        <p>ログインし、マイページをクリック</p>
        <p>一番下のグループ作成をクリック</p>
      </div>
    </div>
  </div>
{% endblock %}

project2/helloengineer/templates/helloengineer/login.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/login.css' %}">
{% endblock %}

{% block content %}
  <form action="{% url 'helloengineer:login' %}" method="post">
    <h2>ログイン</h2>
    {{ form.as_p }}
    <input type="submit" value="Login">
    {% csrf_token %}
  </form>
  <p id="signup"><a href= "{% url 'helloengineer:signup' %}">新規作成</a></p>
{% endblock %}

project2/helloengineer/templates/helloengineer/mypage.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/mypage.css' %}">
{% endblock %}

{% block content %}
  <h2>{{ user.username }}のユーザーページ</h2>
  <div class="profile_all">
    {% if user.profile.user_img %}
      <img class="userimg" src="{{ user.profile.user_img.url }}">
    {% else %}
      <img class="userimg" src="{% static 'helloengineer/img/user_defo.jpg' %}">
    {% endif %}
    <h3>年収：{{ user.profile.income }}</h3>
    <h3>性別:{{ user.profile.get_gender_display }} </h3>
    <h3>誕生日:{{ user.profile.birthday }}</h3>
    <h3>自己紹介：{{ user.profile.intro }}</h3>
  </div>
  <div class="group_center">
  {% for group in user.group_set.all %}
    <div class="group_img_and_title"><a href="{% url 'helloengineer:group_thread' group.pk %}">
      {% if group.group_img %}
        <img class="groupimg" src="{{ group.group_img.url }}" alt="{{ group.title }}">
      {% else %}
        <img class="groupimg" src="{% static 'helloengineer/img/group_defo.jpg' %}" alt="{{ group.title }}">
      {% endif %}
      <h3>{{ group.title }}</h3>
      <form method="post" action="{% url 'helloengineer:delete' group.pk %}">{% csrf_token %}
        <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>{{ group.title }}を削除</button>
      </form>
    </div>
  {% endfor %}
  </div>
  <div class="profile_update">
    <div class="elem"><a href="/helloengineer/group_create">グループ作成</a><br></div>
    <div class="elem"><a href="{% url 'helloengineer:profileupdate' user.pk %}">プロフィール更新</a></div>
    <div class="elem"><a onclick='return confirm("本当にログアウトしますか？");' href="/helloengineer/logout">ログアウト</a><br></div>
  </div>
{% endblock %}

project2/helloengineer/templates/helloengineer/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

project2/helloengineer/templates/helloengineer/profileupdate.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/form.css' %}">
{% endblock %}

{% block content %}
  <h2>プロフィールを更新しますか？</h2>
  <div class="center">
    <form method="POST" class="post-form" enctype="multipart/form-data">
      <div class="sheet">
        {% for field in form %}
          <div class="elem">
            {{ field.label }}:
            {{ field }}
          </div>
        {% endfor %}
        <button type="submit" class="create_button">更新</button>
        {% csrf_token %}
      </div>
    </form>
  </div>
  <p><a href="{% url 'helloengineer:mypage' user.pk %}">マイページに戻る</a></p>
{% endblock %}

project2/helloengineer/templates/helloengineer/signup.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/signup.css' %}">
{% endblock %}

{% block content %}
  <form action="{% url 'helloengineer:signup' %}" method="post">
   {% csrf_token %}
   <h2>新規登録</h2>
   {{ form.as_p }}
   <input type="submit" value="Sign Up">
  </form>
  <p id="login"><a href= "{% url 'helloengineer:login' %}">ログイン</a></p>
{% endblock %}

project2/helloengineer/templates/helloengineer/userpage.html
{% extends 'helloengineer/base.html' %}

{% block header %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'helloengineer/userpage.css' %}">
{% endblock %}

{% block content %}
  <div class="profile_all">
    <h2>{{ user.username }}のユーザーページ</h2>
    {% if user.profile.user_img %}
      <img class="userimg" src="{{ user.profile.user_img.url }}" alt="{{ video.title }}">
    {% else %}
      <img class="userimg" src="{% static 'helloengineer/img/user_defo.jpg' %}" alt="{{ video.title }}">
    {% endif %}
    <h3>年収：{{ user.profile.income }}</h3>
    <h3>性別:{{ user.profile.get_gender_display }} </h3>
    <h3>誕生日:{{ user.profile.birthday }}</h3>
    <h3>自己紹介：{{ user.profile.intro }}</h3>
  <div>
{% endblock %}